### ISSUE TITLE
Domain name

### ISSUE THREAD

**Issue by brechtm** [reStructuredText/startup#2]
Some options are:
- [restructuredtext.org](http://restructuredtext.org/)
  - points to a GitHub 404 page
  - haven't managed to find a matching CNAME file in public GitHub repositories
  - no success yet in contacting the owner (tried [the registrar](http://webform.meshdigital.com/?linkId=102609513) and [Domain Contact](https://www.domain-contact.org/))
- [restructuredtext.net](https://www.restructuredtext.net/)
  - website for a VSCode extension
  - owner isn't interested in making it available to us
- [restructuredtext.com](http://www.restructuredtext.com)
  - very expensive at $2000
  - .com isn't a good fit, anyway

**Comment by webknjaz** [comment]
> * haven't managed to find a matching CNAME file in public GitHub repositories

That's likely because `gh-pages` is often not a default repo branch and thus is not indexed. You could probably ask GH support to contact them.

We could always go for something from the new shiny gTLDs: restructuredtext.dev or restructuredtext.rocks.

**Comment by jdillard** [comment]
Here is a plain text list of TLDs (some, like `.docs` aren't actually purchasable yet): https://data.iana.org/TLD/tlds-alpha-by-domain.txt

I'm usually not a fan of gTLDs, but so far I think I like **restructuredtext.guide** the best.
